version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shopping_db
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: shopping_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: